const User = require('./User');
const Supplier = require('./Supplier');
const Service = require('./Service');
const Product = require('./Product');
const Invoice = require('./Invoice');
const Quote = require('./Quote');
const VisitorLog = require('./VisitorLog');
const GiftCard = require('./GiftCard');
const VisitorCount = require('./VisitorCount');
const QuickQuote = require('./QuickQuote');
const Booking = require('./Booking');
const Role = require('./Role');
const Permission = require('./Permission');
const UserNotificationSettings = require('./UserNotificationSettings');
const CompanyNotificationDefaults = require('./CompanyNotificationDefaults');
const NotificationTemplate = require('./NotificationTemplate');
const NotificationLog = require('./NotificationLog');

module.exports = {User, Supplier, Service, Product, Invoice, Quote, VisitorLog, GiftCard, VisitorCount, QuickQuote, Booking, Role, Permission, UserNotificationSettings, CompanyNotificationDefaults, NotificationTemplate, NotificationLog};